# -*- coding: utf-8 -*-
"""VITONHD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KJFu1GTDp016IovYPVxqE_nDvouzVAR
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git clone https://github.com/shadow2496/VITON-HD.git
# %cd VITON-HD

!pip install torch==1.13.1 torchvision==0.14.1
!pip install opencv-python torchgeometry

!unzip -q zalando-hd-resized.zip -d datasets/

!unzip -q /content/drive/MyDrive/vitonhd/zalando-hd-resized.zip "test/*" -d /content/datasets/

!unzip -q zalando-hd-resized.zip "*openpose-img*" -d /content/datasets/

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/vitonhd

!unzip -o checkpoints.zip -d checkpoints/
!unzip -o test.zip -d datasets/

!CUDA_VISIBLE_DEVICES=0 python test.py --name demo

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/VITON-HD

!unzip /content/drive/MyDrive/vitonhd/checkpoints.zip -d checkpoints/
!unzip /content/drive/MyDrive/vitonhd/test.zip -d datasets/

!mv /content/drive/MyDrive/vitonhd/checkpoints/checkpoints/* /content/drive/MyDrive/vitonhd/checkpoints/

!rmdir /content/drive/MyDrive/vitonhd/checkpoints/checkpoints

ls /content/VITON-HD/vitonhd/checkpoints/

!pip install pyngrok

!ngrok config add-authtoken "30HF91bQql7sxhSoG7g4rL7oQI5_5VhR3PLgZLChcH9W7AKiL"

!pkill -f ngrok

!python3 test.py --name demo

# tüm test_pairs.txt içinden ilk 100 çifti değerlendir
!python evaluation.py \
  --pairs_file datasets/test_pairs.txt \
  --output_dir results/demo \
  --limit 100 \
  --cmd python test.py --name demo

!pip install lpips

!pip install fastapi uvicorn pyngrok
from pyngrok import ngrok

public_url = ngrok.connect(8002)
print(public_url)

!uvicorn viton:app --host 0.0.0.0 --port 8002

!ls -lh ./results/demo

!python3 test.py --name demo

!pip install psutil torch pillow scikit-image numpy